### ISSUE TITLE
req

### ISSUE THREAD

**Issue by vigneshsara** [aagarwal1012/Debug-Thugs#9]

**Comment by vigneshsara** [comment]
hi i have do this project as my final year project ,till i have completed the collection the data(location value and sensor value )and store in firebase(cloud) after the i have stack it ,i have lot of confusion on machine learning to find the holes...pls can you and idea r suggestion

**Comment by aagarwal1012** [comment]
@vigneshsara,
For writing machine learning model,  you can refer this https://github.com/aagarwal1012/Debug-Thugs/blob/final_product/Develop-model/model.ipynb
